spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/voter
    username: voter
    password: voter
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: true
      hibernate.show_sql: false
  flyway:
    enabled: true

server:
  port: 8080